#!/bin/bash

# Stop at fail
set -e

# Ensure script is run as root (via sudo)
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root. Use: sudo ./setup_jupyter_lab.sh"
    exit 1
fi

getPythonCommands() {
    # Use login shell (conda/user PATH is hopefully fully initialized)
    pythonCmd=$(sudo -u main bash -l -c '
        if cmd=$(which python3 2>/dev/null); then
            echo "$cmd"
        elif cmd=$(which python 2>/dev/null); then
            echo "$cmd"
        fi
    ')

    if [ -z "$pythonCmd" ]; then
        echo "Error: No python3/python found in the main user environment."
        exit 1
    fi

    echo "Using Python: $pythonCmd"
    echo "Version: $(sudo -u main "$pythonCmd" --version)"

    pipCmd="$pythonCmd -m pip"
}

askPassword() {
    password=""
    while true; do
        echo -n "New password: "
        read -s pass1
        echo
        echo -n "Confirm password: "
        read -s pass2
        echo

        if [ "$pass1" != "$pass2" ]; then
            echo "Passwords are not equal!"
            continue
        fi
        if [ ${#pass1} -le 2 ]; then
            echo "Password needs at least 3 chars!"
            continue
        fi

        echo "Password seems good!"
        password="$pass1"
        break
    done
}

# Install openssl
apt-get update -y
apt-get install -y sed openssl

# Resolve python
getPythonCommands

# Install jupyter
sudo -u main bash -l -c "$pipCmd install --upgrade pip"
sudo -u main bash -l -c "$pipCmd install jupyterlab"

# Generate config as main user
sudo -u main bash -l -c "jupyter lab --generate-config"

# Ask password
askPassword

# Generate certs
home_dir=$(sudo -u main bash -l -c 'echo $HOME')
crt_file="$home_dir/.jupyter/cert.crt"
key_file="$home_dir/.jupyter/cert.key"
sudo -u main openssl req -new -newkey rsa:4096 -sha256 -nodes -x509 \
    -keyout "$key_file" -out "$crt_file" \
    -subj "/C=DE/ST=Bayern/L=Augsburg/O=Universität Augsburg/OU=Misit/CN=*.informatik.uni-augsburg.de"

# Hash password
hashPwd=$(JUPYTER_PWD="$password" sudo -u main bash -l -c \
    '$PYTHON -c "import os; from jupyter_server.auth import passwd; print(passwd(os.environ[\"JUPYTER_PWD\"]))"' \
    PYTHON="$pythonCmd")

# Write config
cfg_file="$home_dir/.jupyter/jupyter_lab_config.py"
sudo -u main tee "$cfg_file" > /dev/null << EOF
# Auto-generated by setup_jupyter_lab.sh
c.ServerApp.allow_root = True
c.ServerApp.certfile = '$crt_file'
c.ServerApp.ip = '0.0.0.0'
c.ServerApp.keyfile = '$key_file'
c.ServerApp.open_browser = False
c.ServerApp.password = '$hashPwd'
c.ServerApp.password_required = True
c.ServerApp.port = 8888
c.ServerApp.quit_button = False
EOF

echo "Script was successful!"
echo "Start Jupyter Lab with:"
echo "  sudo -u main bash -l -c \"cd ~/ && nohup jupyter lab >~/.jupyter-lab.logs.txt 2>&1 &\""